site_name: Notas Musicais
repo_url: https://github.com/ntc-Felix/notas-musicais
repo_name: ntc-Felix/notas-musicais

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css

# ativando mkdocstring
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [notas_musicais]